# .github/workflows/kivy-ci.yml

name: Kivy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DISPLAY: ":99"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgl1-mesa-glx
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install kivy[base] --extra-index-url https://kivy.org/downloads/simple/

    - name: Run app in headless mode (basic test)
      run: |
        xvfb-run python main.py
